alter session set "_ORACLE_SCRIPT"=true;

CREATE USER DBAX_LITE IDENTIFIED BY dbax ACCOUNT UNLOCK  PROFILE DEFAULT; 

GRANT RESOURCE, CREATE SESSION to DBAX_LITE;

ALTER USER DBAX_LITE QUOTA UNLIMITED ON USERS;
